### ISSUE TITLE
Emulate Facebook app appearance

### ISSUE THREAD

**Issue by jeffrey-tc** [Facebook-AdTech-Research/facebook-data-checkup#1]
- [x] #2 Build Facebook tab bar
- [x] #3 Build notifications header
- [x] #4 Build notification row component
